### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by realchrisolin** [seiichiinoue/cnn-for-musical-onset-detection#5]
```
(venv) C:\Users\Chris Olin\PycharmProjects\onset_detection\cnn-for-musical-onset-detection>python train.py don
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    net = net.to(device)
  File "C:\Users\Chris Olin\PycharmProjects\onset_detection\venv\lib\site-packages\torch\nn\modules\module.py", line 432, in to
    return self._apply(convert)
  File "C:\Users\Chris Olin\PycharmProjects\onset_detection\venv\lib\site-packages\torch\nn\modules\module.py", line 208, in _apply
    module._apply(fn)
  File "C:\Users\Chris Olin\PycharmProjects\onset_detection\venv\lib\site-packages\torch\nn\modules\module.py", line 230, in _apply
    param_applied = fn(param)
  File "C:\Users\Chris Olin\PycharmProjects\onset_detection\venv\lib\site-packages\torch\nn\modules\module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
```

**Comment by realchrisolin** [comment]
I was able to resolve this error by changing line 7 in train.py from
`device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')`
to
`device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')`

**Comment by seiichiinoue** [comment]
thx! fixed that code!
